---
title: "tidyverse"
author: "cxm"
date: "7/8/2020"
output: html_document
---


## R tidyverse

```{r}
library(tidyverse)
as_tibble(iris)
```
```{r}
ggplot(iris) + 
  geom_point(aes(Petal.Length, Petal.Width, 
                 color = Species, shape = Species), size = 3)
```

```{r}
ggplot(iris, aes(Petal.Length, Petal.Width)) + 
  geom_point(aes(color = Species, shape = Species), size = 3) + 
  geom_smooth(color = "black")
```
```{r}
ggplot(iris, aes(Petal.Length, Petal.Width , color=Species)) + 
  geom_point(aes(shape = Species), size = 3)+
  geom_smooth()
  
```
```{r}
ggplot(iris) + 
  geom_point(aes(Petal.Length, Petal.Width, 
                 color = Species, shape = Species), size = 3) + 
  scale_x_log10(breaks = 1:7)
```
```{r}
ggplot(iris) + 
  geom_point(aes(Petal.Length, Petal.Width, 
                 color = Species, shape = Species), size = 3) + 
  facet_grid(~ Species)
```
```{r}
(df <- gapminder::gapminder %>%
   dplyr::filter(year == 1992))
```

```{r}
ggplot(df) + 
  geom_point(aes(gdpPercap, lifeExp, size = pop, 
                 color = continent)) +
  scale_x_log10(breaks = c(300, 1e3, 3e3, 10e3, 30e3)) + 
  labs(title = "Gapminder for 1992",
       x = "Gross Domestic Product (log scale)",
       y = "Life Expectancy at birth (years)",
       color = "Continent", size = "Population")
```

